apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.fullname" . }}-discovery
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ template "elasticsearch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    app: {{ template "elasticsearch.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: transport
